name: Build ALL and Push Artifacts

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build-and-push:
    runs-on: ubuntu-22.04  # 使用 Ubuntu 22.04 显式指定

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set executable permissions for the script
        run: chmod +x ./make_android_lua53.sh  # 给构建脚本加上执行权限

      - name: Run the shell script
        run: ./make_android_lua53.sh  # 运行你的构建脚本

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xlua-shared-library
          path: ./plugin53/android/libxlua.so  # 根据你的构建路径调整文件路径
